"use client"

import type React from "react"

import { createContext, useContext, useEffect, useState } from "react"

type Language = "id" | "en"

interface LanguageContextType {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string, params?: Record<string, string | number>) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Translation dictionaries
const translations = {
  id: {
    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.content-generator": "AI Content Generator",
    "nav.virtual-tutor": "Virtual Tutor",
    "nav.analytics": "Learning Analytics",
    "nav.library": "Materi Pembelajaran",
    "nav.community": "Grup Belajar",
    "nav.settings": "Pengaturan",

    // Dashboard
    "dashboard.welcome": "Selamat datang kembali",
    "dashboard.student.subtitle": "Mari lanjutkan perjalanan belajarmu dengan rekomendasi yang dipersonalisasi",
    "dashboard.teacher.subtitle": "Buat konten edukatif yang menarik dengan bantuan AI",
    "dashboard.professional.subtitle": "Tingkatkan skill profesionalmu dengan pembelajaran adaptif",
    "dashboard.completed-courses": "Kursus Selesai",
    "dashboard.learning-streak": "Streak Belajar",
    "dashboard.total-hours": "Total Jam",
    "dashboard.achievements": "Pencapaian",
    "dashboard.content-created": "Konten Dibuat",
    "dashboard.students-helped": "Siswa Terbantu",
    "dashboard.avg-rating": "Rating Rata-rata",
    "dashboard.teaching-hours": "Jam Mengajar",
    "dashboard.personalized-recommendations": "Rekomendasi Dipersonalisasi",
    "dashboard.recommendations.subtitle": "Berdasarkan minat, level kompetensi, dan riwayat belajar Anda",
    "dashboard.core-features": "Fitur Utama EduGenAI",
    "dashboard.features.subtitle": "Jelajahi kemampuan AI untuk meningkatkan pengalaman belajar",
    "dashboard.virtual-tutor": "Virtual Tutor AI",
    "dashboard.tutor.subtitle": "Asisten AI 24/7 siap membantu",
    "dashboard.learning-progress": "Progress Belajar",
    "dashboard.progress.subtitle": "Pantau kemajuan pembelajaran Anda",
    "dashboard.quick-actions": "Aksi Cepat",

    // Content Generator
    "content-generator.title": "AI Content Generator",
    "content-generator.subtitle": "Buat materi pembelajaran yang menarik dengan bantuan AI dan video YouTube terpilih",
    "content-generator.settings": "Pengaturan Generator",
    "content-generator.settings.subtitle": "Atur parameter untuk menghasilkan konten yang sesuai",
    "content-generator.topic": "Topik Pembelajaran",
    "content-generator.category": "Kategori Mata Pelajaran",
    "content-generator.level": "Level Pendidikan",
    "content-generator.content-type": "Jenis Konten",
    "content-generator.additional": "Instruksi Tambahan (Opsional)",
    "content-generator.generate": "Generate Konten",
    "content-generator.generating": "Generating...",
    "content-generator.ready-to-create": "Siap Membuat Konten?",
    "content-generator.fill-form-to-start": 'Isi form di sebelah kiri dan klik "Generate Konten" untuk memulai',
    "content-generator.creating-content-for": 'Membuat konten pembelajaran untuk "{{topic}}"',
    "content-generator.content-generated": "Konten Berhasil Dibuat!",
    "content-generator.content-generated-description":
      "AI telah menghasilkan materi pembelajaran lengkap dengan video YouTube terpilih",

    // Virtual Tutor
    "virtual-tutor.title": "Virtual Tutor AI",
    "virtual-tutor.subtitle": "Asisten pembelajaran AI dengan teknologi machine learning terdepan",
    "virtual-tutor.online": "AI Online",
    "virtual-tutor.powered-by": "Powered by GPT-4",
    "virtual-tutor.machine-learning": "Machine Learning",
    "virtual-tutor.ready-to-help": "Siap membantu dengan AI & Machine Learning",
    "virtual-tutor.popular-questions": "Pertanyaan Populer",
    "virtual-tutor.questions.subtitle": "Klik untuk bertanya langsung",
    "virtual-tutor.ai-capabilities": "Kemampuan AI",
    "virtual-tutor.placeholder": "Tanya apa saja tentang pelajaran...",
    "virtual-tutor.tip": "Tips: Semakin spesifik pertanyaan Anda, semakin detail jawaban AI",
    "virtual-tutor.setup-api-key": "Setup OpenAI API Key",
    "virtual-tutor.api-key-description": "Untuk menggunakan AI Tutor, Anda perlu menambahkan OpenAI API Key",
    "virtual-tutor.how-to-get-api-key": "Cara Mendapatkan API Key",
    "virtual-tutor.visit": "Kunjungi",
    "virtual-tutor.login-or-register": "Login atau daftar akun OpenAI",
    "virtual-tutor.create-new-key": 'Klik "Create new secret key"',
    "virtual-tutor.copy-key": "Copy API key yang dihasilkan",
    "virtual-tutor.paste-key": "Paste di form di bawah ini",
    "virtual-tutor.api-key-temp-storage": "API key akan disimpan sementara untuk sesi ini saja",
    "virtual-tutor.for-production": "Untuk Production",
    "virtual-tutor.add-env-var": "Tambahkan",
    "virtual-tutor.in-file": "di file",
    "virtual-tutor.or-env-vars": "atau Environment Variables",
    "virtual-tutor.use-api-key": "Gunakan API Key",
    "virtual-tutor.api-key-not-set": "⚠️ API key belum disetel. Silakan setup API key terlebih dahulu.",
    "virtual-tutor.api-key-invalid-format":
      'Format API key tidak valid. Pastikan dimulai dengan "sk-" dan memiliki panjang yang sesuai.',
    "virtual-tutor.api-key-validation-error": "Terjadi kesalahan saat memvalidasi API key.",
    "virtual-tutor.initial-greeting":
      "Halo {{name}}! 👋 \n\nSaya adalah AI Tutor EduGenAI, asisten pembelajaran cerdas yang siap membantu Anda 24/7. Saya menggunakan teknologi machine learning terdepan untuk memberikan penjelasan yang personal dan mudah dipahami.\n\n**Apa yang bisa saya bantu hari ini?**\n- 📚 Penjelasan konsep dengan contoh praktis\n- 🧮 Pemecahan soal matematika step-by-step  \n- 🔬 Eksperimen sains virtual\n- 📝 Bantuan mengerjakan PR\n- 🎯 Tips belajar yang efektif\n\nSilakan tanya apa saja yang ingin Anda pelajari!",
    "virtual-tutor.fallback-response":
      'Maaf, saya mengalami sedikit gangguan teknis. Namun saya tetap bisa membantu Anda! \n\nUntuk pertanyaan "{{content}}", saya sarankan:\n\n1. **Coba pecah pertanyaan** menjadi bagian-bagian kecil\n2. **Cari kata kunci utama** dari topik yang ingin dipelajari  \n3. **Hubungkan dengan konsep** yang sudah Anda pahami sebelumnya\n\nSilakan coba tanya lagi dengan cara yang berbeda, atau pilih salah satu pertanyaan cepat. Saya siap membantu! 😊',

    // Library
    "library.title": "Materi Pembelajaran",
    "library.subtitle": "Koleksi lengkap materi pembelajaran berkualitas tinggi dengan video YouTube terpilih",
    "library.search": "Cari materi pembelajaran...",
    "library.all-categories": "Semua Kategori",
    "library.all-levels": "Semua Level",
    "library.featured": "Unggulan",
    "library.youtube": "Video YouTube",
    "library.recent": "Terbaru",
    "library.popular": "Populer",
    "library.bookmarks": "Tersimpan",
    "library.select-category-level": "Pilih Kategori dan Level",
    "library.select-category-level-description":
      "Pilih kategori mata pelajaran dan level pendidikan untuk melihat video YouTube yang relevan",
    "library.searching-videos-description": "Sedang mencari video YouTube terbaik untuk {{category}} tingkat {{level}}",
    "library.no-videos-found": "Tidak Ada Video Ditemukan",
    "library.no-videos-found-description":
      "Coba ubah kategori atau level, atau gunakan kata kunci pencarian yang berbeda",
    "library.no-bookmarks": "Belum Ada Materi Tersimpan",
    "library.no-bookmarks-description": "Simpan materi pembelajaran favorit Anda untuk akses yang lebih mudah",
    "library.explore-library": "Jelajahi Perpustakaan",
    "library.trending-this-week": "Trending Minggu Ini",
    "library.highest-rated": "Rating Tertinggi",

    // Community
    "community.title": "Grup Belajar InsanAI",
    "community.subtitle": "Bergabunglah dengan grup belajar untuk berbagi pengetahuan dan saling membantu",
    "community.search": "Cari diskusi, pertanyaan, atau topik...",
    "community.create-discussion": "Buat Diskusi Baru",
    "community.discussions": "Diskusi",
    "community.study-groups": "Grup Belajar",
    "community.qa": "Q&A",
    "community.start-new-discussion": "Mulai Diskusi Baru",
    "community.discussion-title-placeholder": "Judul diskusi atau pertanyaan...",
    "community.discussion-content-placeholder": "Tulis pertanyaan atau topik diskusi Anda...",
    "community.select-category": "Pilih kategori",
    "community.add-tag-placeholder": "Tambah tag (tekan Enter)",
    "community.post": "Posting",
    "community.fill-all-fields": "Harap isi semua kolom yang diperlukan.",
    "community.post-success": "Diskusi berhasil diposting!",
    "community.no-study-groups": "Belum Ada Grup Belajar",
    "community.no-study-groups-description": "Buat atau bergabunglah dengan grup belajar untuk kolaborasi",
    "community.create-study-group": "Buat Grup Belajar",
    "community.qa-title": "Tanya Jawab Komunitas",
    "community.qa-description": "Ajukan pertanyaan dan dapatkan jawaban dari para ahli dan sesama pembelajar",
    "community.ask-question": "Ajukan Pertanyaan",
    "community.community-stats": "Statistik Komunitas",
    "community.total-members": "Total Anggota",
    "community.active-discussions": "Diskusi Aktif",
    "community.answered-questions": "Pertanyaan Terjawab",
    "community.online-now": "Online Sekarang",
    "community.share-tips": "Berbagi Tips",
    "community.find-study-buddy": "Cari Teman Belajar",

    // Analytics
    "analytics.title": "Learning Analytics",
    "analytics.subtitle": "Dashboard komprehensif untuk memantau perkembangan dan performa pembelajaran",
    "analytics.total-students": "Total Siswa",
    "analytics.avg-score": "Rata-rata Nilai",
    "analytics.learning-hours": "Jam Belajar",
    "analytics.completed-materials": "Materi Selesai",
    "analytics.performance": "Performa",
    "analytics.subjects": "Mata Pelajaran",
    "analytics.students": "Siswa",
    "analytics.insights": "AI Insights",
    "analytics.performance-trend": "Tren Performa 6 Bulan Terakhir",
    "analytics.performance-trend-description": "Perkembangan nilai rata-rata per mata pelajaran",
    "analytics.weekly-activity": "Aktivitas Belajar Mingguan",
    "analytics.weekly-activity-description": "Jam belajar per hari dalam seminggu",
    "analytics.time-distribution": "Distribusi Waktu Belajar",
    "analytics.time-distribution-description": "Persentase waktu yang dihabiskan per mata pelajaran",
    "analytics.areas-of-attention": "Area yang Perlu Perhatian",
    "analytics.areas-of-attention-description": "Rekomendasi AI berdasarkan analisis performa",
    "analytics.individual-student-performance": "Performa Individual Siswa",
    "analytics.individual-student-performance-description":
      "Monitoring progress dan identifikasi siswa yang membutuhkan bantuan",
    "analytics.ai-insights-predictions": "AI Insights & Prediksi",
    "analytics.ai-insights-predictions-description": "Analisis mendalam dan rekomendasi berbasis AI",
    "analytics.learning-optimization": "Optimasi Pembelajaran",
    "analytics.learning-optimization-description": "Saran untuk meningkatkan efektivitas pembelajaran",

    // Settings
    "settings.title": "Pengaturan",
    "settings.subtitle": "Kelola profil, preferensi, dan pengaturan akun Anda",
    "settings.profile": "Profil",
    "settings.preferences": "Preferensi",
    "settings.notifications": "Notifikasi",
    "settings.ai-settings": "Pengaturan AI",
    "settings.data": "Data & Privasi",
    "settings.profile-info": "Informasi Profil",
    "settings.profile.subtitle": "Kelola informasi dasar akun Anda",
    "settings.full-name": "Nama Lengkap",
    "settings.email": "Email",
    "settings.role": "Peran",
    "settings.phone": "Nomor Telepon",
    "settings.save-changes": "Simpan Perubahan",
    "settings.saving": "Menyimpan...",
    "settings.cancel": "Batal",
    "settings.appearance": "Tampilan",
    "settings.appearance.subtitle": "Sesuaikan tampilan aplikasi",
    "settings.theme": "Tema",
    "settings.theme.subtitle": "Pilih tema yang Anda sukai",
    "settings.theme.light": "Terang",
    "settings.theme.dark": "Gelap",
    "settings.theme.system": "Sistem",
    "settings.language-region": "Bahasa & Region",
    "settings.language-region.subtitle": "Pengaturan bahasa dan lokasi",
    "settings.language": "Bahasa",
    "settings.language.subtitle": "Bahasa antarmuka aplikasi",
    "settings.language.id": "Indonesia",
    "settings.language.en": "English",

    // Common
    "common.start": "Mulai",
    "common.open": "Buka",
    "common.download": "Download",
    "common.share": "Share",
    "common.save": "Simpan",
    "common.cancel": "Batal",
    "common.search": "Cari",
    "common.filter": "Filter",
    "common.loading": "Memuat...",
    "common.error": "Terjadi kesalahan",
    "common.success": "Berhasil",
    "common.student": "Siswa",
    "common.teacher": "Guru",
    "common.professional": "Profesional",
    "common.beginner": "Pemula",
    "common.intermediate": "Menengah",
    "common.advanced": "Lanjutan",
    "common.expert": "Ahli",
    "common.this-week": "minggu ini",
    "common.this-month": "bulan ini",
    "common.today": "Hari ini",
    "common.one-day-ago": "1 hari yang lalu",
    "common.days-ago": "{{count}} hari yang lalu",
    "common.weeks-ago": "{{count}} minggu yang lalu",
    "common.months-ago": "{{count}} bulan yang lalu",
    "common.by": "oleh",
    "common.watch": "Tonton",
    "common.preview": "Pratinjau",
    "common.dark-mode-active": "🌙 Mode gelap aktif",
    "common.light-mode-active": "☀️ Mode terang aktif",
    "common.language-preview": "Pratinjau Bahasa",
    "common.id-interface-description": "Antarmuka aplikasi akan ditampilkan dalam Bahasa Indonesia",
    "common.en-interface-description": "Antarmuka aplikasi akan ditampilkan dalam Bahasa Inggris",
    "common.changes-applied-automatically": "Perubahan akan diterapkan secara otomatis",
    "common.validating": "Validating...",
    "common.from-last-month": "dari bulan lalu",
    "common.points": "poin",
    "common.target-achieved": "target tercapai",
    "common.others": "Lainnya",
    "common.needs-more-practice": "Perlu Latihan Lebih",
    "common.students-struggle-linear-equations": "siswa mengalami kesulitan dengan konsep persamaan linear",
    "common.recommend-tutorial-videos": "Rekomendasikan video tutorial dan latihan tambahan",
    "common.momentum": "Momentum",
    "common.momentum-concept-needs-visuals": "Konsep momentum dan impuls perlu penjelasan visual lebih banyak",
    "common.use-interactive-simulations": "Gunakan simulasi interaktif",
    "common.excellent": "Sangat Baik",
    "common.good": "Baik",
    "common.average": "Rata-rata",
    "common.needs-attention": "Perlu Perhatian",
    "common.hours": "jam",
    "common.minutes": "menit",
    "common.positive-trend": "Tren Positif",
    "common.math-performance-increased":
      "Performa matematika meningkat 12% dalam 3 bulan terakhir. Metode gamifikasi terbukti efektif untuk topik aljabar",
    "common.risk-prediction": "Prediksi Risiko",
    "common.students-at-risk":
      "siswa berisiko tidak mencapai target semester. Rekomendasikan sesi tutoring tambahan dalam 2 minggu ke depan",
    "common.recommendation": "Rekomendasi",
    "common.implement-more-virtual-practicums": "Implementasikan lebih banyak praktikum virtual untuk fisika",
    "common.engagement-rate-increased": "Engagement rate meningkat 34% dengan metode ini",
    "common.learning-optimization": "Optimasi Pembelajaran",
    "common.learning-optimization-description": "Saran untuk meningkatkan efektivitas pembelajaran",
    "common.personalize-content": "Personalisasi Konten",
    "common.adjust-difficulty-based-on-performance":
      "Sesuaikan tingkat kesulitan berdasarkan performa individual siswa",
    "common.optimal-time": "Waktu Optimal",
    "common.schedule-difficult-material": "Jadwalkan materi sulit pada jam 09:00-11:00 untuk hasil terbaik",
    "common.interactive-methods": "Metode Interaktif",
    "common.increase-simulation-gamification": "Tingkatkan penggunaan simulasi dan gamifikasi untuk engagement",
    "common.real-time-feedback": "Feedback Real-time",
    "common.implement-auto-feedback": "Implementasikan sistem feedback otomatis untuk koreksi cepat",
    "common.learning": "pembelajaran",
    "common.searching-videos": "Mencari Video...",
    "common.selected-learning-videos": "Video Pembelajaran Terpilih",
    "common.high-quality-youtube-videos":
      "Video YouTube berkualitas tinggi yang dipilih AI berdasarkan relevansi dan rating",
    "common.main-recommendation": "Rekomendasi Utama",
    "common.presentation": "Presentasi",
    "common.ready-to-use-powerpoint": "Presentasi PowerPoint siap pakai dengan {{slides}} slide",
    "common.preview-structure": "Preview Struktur",
    "common.slides": "slides",
    "common.download-ppt": "Download PPT",
    "common.quiz": "Kuis",
    "common.interactive-assessment-description": "Assessment interaktif untuk mengukur pemahaman siswa",
    "common.questions": "Pertanyaan",
    "common.question-types": "Jenis Soal",
    "common.level": "Level",
    "common.multiple-choice": "Pilihan Ganda",
    "common.short-answer": "Isian Singkat",
    "common.true-false": "Benar/Salah",
    "common.estimated-time": "Estimasi waktu",
    "common.export-quiz": "Export Quiz",
    "common.resources": "Sumber Belajar",
    "common.additional-learning-resources": "Sumber Belajar Tambahan",
    "common.complete-collection-of-videos": "Koleksi lengkap video pembelajaran dari berbagai channel terpercaya",
    "common.videos-available": "Video Tersedia",
    "common.total-duration": "Total Durasi",
    "common.channels": "Channel",
    "common.trusted-channels": "Channel Terpercaya",
    "common.all-videos": "Semua Video",
    "common.ai-working": "AI Sedang Bekerja",
    "common.analyzing-topic-level": "Menganalisis topik dan level pendidikan",
    "common.searching-youtube-videos": "Mencari video YouTube terbaik",
    "common.structuring-learning": "Menyusun struktur pembelajaran",
    "common.generating-multimedia-content": "Menghasilkan konten multimedia",
    "common.select-category": "Pilih kategori",
    "common.select-level": "Pilih level",
    "common.select-content-type": "Pilih jenis konten",
    "common.general-discussion": "Diskusi Umum",
  },
  en: {
    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.content-generator": "AI Content Generator",
    "nav.virtual-tutor": "Virtual Tutor",
    "nav.analytics": "Learning Analytics",
    "nav.library": "Library",
    "nav.community": "Community",
    "nav.settings": "Settings",

    // Dashboard
    "dashboard.welcome": "Welcome back",
    "dashboard.student.subtitle": "Continue your learning journey with personalized recommendations",
    "dashboard.teacher.subtitle": "Create engaging educational content with AI assistance",
    "dashboard.professional.subtitle": "Enhance your professional skills with adaptive learning",
    "dashboard.completed-courses": "Completed Courses",
    "dashboard.learning-streak": "Learning Streak",
    "dashboard.total-hours": "Total Hours",
    "dashboard.achievements": "Achievements",
    "dashboard.content-created": "Content Created",
    "dashboard.students-helped": "Students Helped",
    "dashboard.avg-rating": "Average Rating",
    "dashboard.teaching-hours": "Teaching Hours",
    "dashboard.personalized-recommendations": "Personalized Recommendations",
    "dashboard.recommendations.subtitle": "Based on your interests, competency level, and learning history",
    "dashboard.core-features": "EduGenAI Core Features",
    "dashboard.features.subtitle": "Explore AI capabilities to enhance your learning experience",
    "dashboard.virtual-tutor": "Virtual AI Tutor",
    "dashboard.tutor.subtitle": "24/7 AI assistant ready to help",
    "dashboard.learning-progress": "Learning Progress",
    "dashboard.progress.subtitle": "Track your learning advancement",
    "dashboard.quick-actions": "Quick Actions",

    // Content Generator
    "content-generator.title": "AI Content Generator",
    "content-generator.subtitle": "Create engaging learning materials with AI assistance and curated YouTube videos",
    "content-generator.settings": "Generator Settings",
    "content-generator.settings.subtitle": "Configure parameters to generate suitable content",
    "content-generator.topic": "Learning Topic",
    "content-generator.category": "Subject Category",
    "content-generator.level": "Education Level",
    "content-generator.content-type": "Content Type",
    "content-generator.additional": "Additional Instructions (Optional)",
    "content-generator.generate": "Generate Content",
    "content-generator.generating": "Generating...",
    "content-generator.ready-to-create": "Ready to Create Content?",
    "content-generator.fill-form-to-start": 'Fill the form on the left and click "Generate Content" to start',
    "content-generator.creating-content-for": 'Creating learning content for "{{topic}}"',
    "content-generator.content-generated": "Content Successfully Generated!",
    "content-generator.content-generated-description":
      "AI has generated complete learning materials with selected YouTube videos",

    // Virtual Tutor
    "virtual-tutor.title": "Virtual AI Tutor",
    "virtual-tutor.subtitle": "AI learning assistant with cutting-edge machine learning technology",
    "virtual-tutor.online": "AI Online",
    "virtual-tutor.powered-by": "Powered by GPT-4",
    "virtual-tutor.machine-learning": "Machine Learning",
    "virtual-tutor.ready-to-help": "Ready to help with AI & Machine Learning",
    "virtual-tutor.popular-questions": "Popular Questions",
    "virtual-tutor.questions.subtitle": "Click to ask directly",
    "virtual-tutor.ai-capabilities": "AI Capabilities",
    "virtual-tutor.placeholder": "Ask anything about your studies...",
    "virtual-tutor.tip": "Tip: The more specific your question, the more detailed the AI response",
    "virtual-tutor.setup-api-key": "Setup OpenAI API Key",
    "virtual-tutor.api-key-description": "To use AI Tutor, you need to add an OpenAI API Key",
    "virtual-tutor.how-to-get-api-key": "How to Get API Key",
    "virtual-tutor.visit": "Visit",
    "virtual-tutor.login-or-register": "Login or register an OpenAI account",
    "virtual-tutor.create-new-key": 'Click "Create new secret key"',
    "virtual-tutor.copy-key": "Copy the generated API key",
    "virtual-tutor.paste-key": "Paste it in the form below",
    "virtual-tutor.api-key-temp-storage": "API key will be temporarily stored for this session only",
    "virtual-tutor.for-production": "For Production",
    "virtual-tutor.add-env-var": "Add",
    "virtual-tutor.in-file": "in the file",
    "virtual-tutor.or-env-vars": "or Environment Variables",
    "virtual-tutor.use-api-key": "Use API Key",
    "virtual-tutor.api-key-not-set": "⚠️ API key not set. Please set up the API key first.",
    "virtual-tutor.api-key-invalid-format":
      'Invalid API key format. Make sure it starts with "sk-" and has the correct length.',
    "virtual-tutor.api-key-validation-error": "An error occurred while validating the API key.",
    "virtual-tutor.initial-greeting":
      "Hello {{name}}! 👋 \n\nI am EduGenAI AI Tutor, a smart learning assistant ready to help you 24/7. I use cutting-edge machine learning technology to provide personalized and easy-to-understand explanations.\n\n**How can I help you today?**\n- 📚 Concept explanations with practical examples\n- 🧮 Step-by-step math problem solving  \n- 🔬 Virtual science experiments\n- 📝 Homework assistance\n- 🎯 Effective study tips\n\nFeel free to ask anything you want to learn!",
    "virtual-tutor.fallback-response":
      "Sorry, I'm experiencing a slight technical issue. But I can still help you! \n\nFor the question \"{{content}}\", I suggest:\n\n1. **Try breaking down the question** into smaller parts\n2. **Look for main keywords** of the topic you want to learn  \n3. **Connect it with concepts** you already understand\n\nPlease try asking again in a different way, or choose one of the quick questions. I'm ready to help! 😊",

    // Library
    "library.title": "Digital Library",
    "library.subtitle": "Complete collection of high-quality learning materials with curated YouTube videos",
    "library.search": "Search learning materials...",
    "library.all-categories": "All Categories",
    "library.all-levels": "All Levels",
    "library.featured": "Featured",
    "library.youtube": "YouTube Videos",
    "library.recent": "Recent",
    "library.popular": "Popular",
    "library.bookmarks": "Bookmarked",
    "library.select-category-level": "Select Category and Level",
    "library.select-category-level-description":
      "Select a subject category and education level to view relevant YouTube videos",
    "library.searching-videos-description": "Searching for the best YouTube videos for {{category}} level {{level}}",
    "library.no-videos-found": "No Videos Found",
    "library.no-videos-found-description": "Try changing the category or level, or use different search keywords",
    "library.no-bookmarks": "No Bookmarked Materials Yet",
    "library.no-bookmarks-description": "Save your favorite learning materials for easier access",
    "library.explore-library": "Explore Library",
    "library.trending-this-week": "Trending This Week",
    "library.highest-rated": "Highest Rated",

    // Community
    "community.title": "EduGenAI Community",
    "community.subtitle": "Join the learning community to share knowledge and help each other",
    "community.search": "Search discussions, questions, or topics...",
    "community.create-discussion": "Create New Discussion",
    "community.discussions": "Discussions",
    "community.study-groups": "Study Groups",
    "community.qa": "Q&A",
    "community.start-new-discussion": "Start New Discussion",
    "community.discussion-title-placeholder": "Discussion title or question...",
    "community.discussion-content-placeholder": "Write your question or discussion topic...",
    "community.select-category": "Select category",
    "community.add-tag-placeholder": "Add tag (press Enter)",
    "community.post": "Post",
    "community.fill-all-fields": "Please fill in all required fields.",
    "community.post-success": "Discussion posted successfully!",
    "community.no-study-groups": "No Study Groups Yet",
    "community.no-study-groups-description": "Create or join a study group for collaboration",
    "community.create-study-group": "Create Study Group",
    "community.qa-title": "Community Q&A",
    "community.qa-description": "Ask questions and get answers from experts and fellow learners",
    "community.ask-question": "Ask a Question",
    "community.community-stats": "Community Statistics",
    "community.total-members": "Total Members",
    "community.active-discussions": "Active Discussions",
    "community.answered-questions": "Answered Questions",
    "community.online-now": "Online Now",
    "community.share-tips": "Share Tips",
    "community.find-study-buddy": "Find a Study Buddy",

    // Analytics
    "analytics.title": "Learning Analytics",
    "analytics.subtitle": "Comprehensive dashboard to monitor learning progress and performance",
    "analytics.total-students": "Total Students",
    "analytics.avg-score": "Average Score",
    "analytics.learning-hours": "Learning Hours",
    "analytics.completed-materials": "Completed Materials",
    "analytics.performance": "Performance",
    "analytics.subjects": "Subjects",
    "analytics.students": "Students",
    "analytics.insights": "AI Insights",
    "analytics.performance-trend": "6-Month Performance Trend",
    "analytics.performance-trend-description": "Average score development per subject",
    "analytics.weekly-activity": "Weekly Learning Activity",
    "analytics.weekly-activity-description": "Hours studied per day in a week",
    "analytics.time-distribution": "Study Time Distribution",
    "analytics.time-distribution-description": "Percentage of time spent per subject",
    "analytics.areas-of-attention": "Areas Needing Attention",
    "analytics.areas-of-attention-description": "AI-based recommendations from performance analysis",
    "analytics.individual-student-performance": "Individual Student Performance",
    "analytics.individual-student-performance-description":
      "Monitoring progress and identifying students who need help",
    "analytics.ai-insights-predictions": "AI Insights & Predictions",
    "analytics.ai-insights-predictions-description": "In-depth analysis and AI-based recommendations",
    "analytics.learning-optimization": "Learning Optimization",
    "analytics.learning-optimization-description": "Suggestions to improve learning effectiveness",

    // Settings
    "settings.title": "Settings",
    "settings.subtitle": "Manage your profile, preferences, and account settings",
    "settings.profile": "Profile",
    "settings.preferences": "Preferences",
    "settings.notifications": "Notifications",
    "settings.ai-settings": "AI Settings",
    "settings.data": "Data & Privacy",
    "settings.profile-info": "Profile Information",
    "settings.profile.subtitle": "Manage your basic account information",
    "settings.full-name": "Full Name",
    "settings.email": "Email",
    "settings.role": "Role",
    "settings.phone": "Phone Number",
    "settings.save-changes": "Save Changes",
    "settings.saving": "Saving...",
    "settings.cancel": "Cancel",
    "settings.appearance": "Appearance",
    "settings.appearance.subtitle": "Customize app appearance",
    "settings.theme": "Theme",
    "settings.theme.subtitle": "Choose your preferred theme",
    "settings.theme.light": "Light",
    "settings.theme.dark": "Dark",
    "settings.theme.system": "System",
    "settings.language-region": "Language & Region",
    "settings.language-region.subtitle": "Language and location settings",
    "settings.language": "Language",
    "settings.language.subtitle": "Application interface language",
    "settings.language.id": "Indonesia",
    "settings.language.en": "English",

    // Common
    "common.start": "Start",
    "common.open": "Open",
    "common.download": "Download",
    "common.share": "Share",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.loading": "Loading...",
    "common.error": "An error occurred",
    "common.success": "Success",
    "common.student": "Student",
    "common.teacher": "Teacher",
    "common.professional": "Professional",
    "common.beginner": "Beginner",
    "common.intermediate": "Intermediate",
    "common.advanced": "Advanced",
    "common.expert": "Expert",
    "common.this-week": "this week",
    "common.this-month": "this month",
    "common.today": "Today",
    "common.one-day-ago": "1 day ago",
    "common.days-ago": "{{count}} days ago",
    "common.weeks-ago": "{{count}} weeks ago",
    "common.months-ago": "{{count}} months ago",
    "common.by": "by",
    "common.watch": "Watch",
    "common.preview": "Preview",
    "common.dark-mode-active": "🌙 Dark mode active",
    "common.light-mode-active": "☀️ Light mode active",
    "common.language-preview": "Language Preview",
    "common.id-interface-description": "Application interface will be displayed in Indonesian",
    "common.en-interface-description": "Application interface will be displayed in English",
    "common.changes-applied-automatically": "Changes will be applied automatically",
    "common.validating": "Validating...",
    "common.from-last-month": "from last month",
    "common.points": "points",
    "common.target-achieved": "target achieved",
    "common.others": "Others",
    "common.needs-more-practice": "Needs More Practice",
    "common.students-struggle-linear-equations": "students struggle with linear equation concepts",
    "common.recommend-tutorial-videos": "Recommend tutorial videos and additional exercises",
    "common.momentum": "Momentum",
    "common.momentum-concept-needs-visuals": "Momentum and impulse concepts need more visual explanations",
    "common.use-interactive-simulations": "Use interactive simulations",
    "common.excellent": "Excellent",
    "common.good": "Good",
    "common.average": "Average",
    "common.needs-attention": "Needs Attention",
    "common.hours": "hours",
    "common.minutes": "minutes",
    "common.positive-trend": "Positive Trend",
    "common.math-performance-increased":
      "Math performance increased by 12% in the last 3 months. Gamification method proven effective for algebra topics",
    "common.risk-prediction": "Risk Prediction",
    "common.students-at-risk":
      "students are at risk of not meeting semester targets. Recommend additional tutoring sessions in the next 2 weeks",
    "common.recommendation": "Recommendation",
    "common.implement-more-virtual-practicums": "Implement more virtual practicums for physics",
    "common.engagement-rate-increased": "Engagement rate increased by 34% with this method",
    "common.learning-optimization": "Learning Optimization",
    "common.learning-optimization-description": "Suggestions to improve learning effectiveness",
    "common.personalize-content": "Personalize Content",
    "common.adjust-difficulty-based-on-performance": "Adjust difficulty level based on individual student performance",
    "common.optimal-time": "Optimal Time",
    "common.schedule-difficult-material": "Schedule difficult material between 09:00-11:00 for best results",
    "common.interactive-methods": "Interactive Methods",
    "common.increase-simulation-gamification": "Increase the use of simulations and gamification for engagement",
    "common.real-time-feedback": "Real-time Feedback",
    "common.implement-auto-feedback": "Implement automated feedback system for quick corrections",
    "common.learning": "learning",
    "common.searching-videos": "Searching Videos...",
    "common.selected-learning-videos": "Selected Learning Videos",
    "common.high-quality-youtube-videos": "High-quality YouTube videos selected by AI based on relevance and rating",
    "common.main-recommendation": "Main Recommendation",
    "common.presentation": "Presentation",
    "common.ready-to-use-powerpoint": "Ready-to-use PowerPoint presentation with {{slides}} slides",
    "common.preview-structure": "Preview Structure",
    "common.slides": "slides",
    "common.download-ppt": "Download PPT",
    "common.quiz": "Quiz",
    "common.interactive-assessment-description": "Interactive assessment to measure student understanding",
    "common.questions": "Questions",
    "common.question-types": "Question Types",
    "common.level": "Level",
    "common.multiple-choice": "Multiple Choice",
    "common.short-answer": "Short Answer",
    "common.true-false": "True/False",
    "common.estimated-time": "Estimated time",
    "common.export-quiz": "Export Quiz",
    "common.resources": "Resources",
    "common.additional-learning-resources": "Additional Learning Resources",
    "common.complete-collection-of-videos": "Complete collection of learning videos from trusted channels",
    "common.videos-available": "Videos Available",
    "common.total-duration": "Total Duration",
    "common.channels": "Channels",
    "common.trusted-channels": "Trusted Channels",
    "common.all-videos": "All Videos",
    "common.ai-working": "AI is Working",
    "common.analyzing-topic-level": "Analyzing topic and education level",
    "common.searching-youtube-videos": "Searching for best YouTube videos",
    "common.structuring-learning": "Structuring learning",
    "common.generating-multimedia-content": "Generating multimedia content",
    "common.select-category": "Select category",
    "common.select-level": "Select level",
    "common.select-content-type": "Select content type",
    "common.general-discussion": "General Discussion",
  },
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("id")

  useEffect(() => {
    // Load language from localStorage on mount
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage) {
      setLanguage(savedLanguage)
    }
  }, [])

  useEffect(() => {
    // Save to localStorage when language changes
    localStorage.setItem("language", language)

    // Update document language attribute
    document.documentElement.lang = language
  }, [language])

  const t = (key: string, params?: Record<string, string | number>): string => {
    let translatedText = translations[language][key as keyof (typeof translations)[typeof language]] || key

    if (params) {
      for (const paramKey in params) {
        translatedText = translatedText.replace(new RegExp(`{{${paramKey}}}`, "g"), String(params[paramKey]))
      }
    }
    return translatedText
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
